name: Publish JupyterBook to GitHub Pages

on:
  push: # trigger build only when push to main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip graphviz
        pip install -r requirements.txt
        pip install ghp-import
        PATH="${PATH}:${HOME}/.local/bin"

    - name: version list
      run: |
        jupyter-book --version
        pip list | grep -i docutils

    - name: Build book HTML
      run: |
        jupyter-book build --all ./content

    - name: Push _build/html to gh-pages
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"

        ghp-import ./content/_build/html -f -p -n
